### ISSUE TITLE
Segfault on startup if no password in accounts.conf

### ISSUE THREAD

**Issue by qwence** [SirCmpwn/aerc#69]
I built this, copied the config to ~/.config/aerc and added one account to accounts.conf:

    [Personal]
    source=imaps://<username>@imap.gmail.com:993

I'm assuming the fact that "password" is in brackets in the example config means that this is supposed to be optional? (i.e. if you don't put a password in the config it should prompt for one)

I'm getting an immediate segfault after running `aerc`, which doesn't occur if I include a password:

#0  0x00007fcec9b91d36 in strlen () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x0000000000413f6e in handle_worker_connect (pipe=0x21e5380, message=0x21e54a0) at <...>/aerc/src/imap/worker/connect.c:55
        imap = 0x7fcec40008c0
        uri = 0x7fcec40009c0
        ssl = true
        res = false
#2  0x00000000004149ce in handle_message (pipe=0x21e5380, message=0x21e54a0) at <...>/aerc/src/imap/worker/worker.c:39
        i = 0
#3  0x000000000041509d in imap_worker (_pipe=0x21e5380) at <...>/aerc/src/imap/worker/worker.c:150
        sleep = true
        pipe = 0x21e5380
        message = 0x21e54a0
        imap = 0x7fcec40008c0
#4  0x00007fceca9be2e7 in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#5  0x00007fcec9bfc54f in clone () from /usr/lib/libc.so.6
No symbol table info available.

**Comment by SirCmpwn** [comment]
It's not optional at the moment, though a prompt would be nice. It shouldn't segfault, though, we should fix that.

**Comment by torpak** [comment]
I get the same with a username containing an @

**Comment by SirCmpwn** [comment]
You need to URL encode it.
